name: amex

channels:
  - defaults
  - conda-forge

dependencies:
  - mamba=0.25.0
  - python=3.8.13
  - pip=22.1.2
  - pandas=1.4.3
  - scikit-learn=1.1.1
  - bayesian-optimization=1.2.0
  - jupyterlab=3.4.4
  - dvc-gs=2.17.0
  - pip:
    - kaggle==1.5.12
    - lightgbm==3.3.2
    - xgboost==1.6.1
    - google-api-python-client==2.56.0